- name: ensure influxdb is installed
  pacman:
    name:
      - influxdb
      - python-influxdb
      - python-requests


- name: ensure influxdb is enabled and running
  systemd:
    state: started
    enabled: yes
    name: influxdb

- name: ensure home database is created
  influxdb_database:
    database_name: "home"

