- name: ensure influxdb is installed
  pacman:
    name:
      - influxdb
      - python-influxdb
      - python-requests


- name: ensure influxdb is enabled and running
  systemd:
    state: started
    enabled: yes
    name: influxdb

